pipeline {
    agent any
    stages {
        stage('Checkout repository') {
            /* Let's make sure we have the repository cloned to our workspace */
            steps {
                checkout scm
            }
        }

        stage('Compile app') {
            /* build the JAR file */
            dir('Engine') {
                steps {
                    sh 'mvn clean install -Dmaven.test.skip=true'
                }
            }
        }
    }
}

